# Defines the containers 
services:
  # First project container (can be named anything)
  db:
    image: postgres:17.0 
    restart: always
    ports:
      - '5433:5432' # expose 5433 on host and sent to 5432 in container
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Postgres
      - POSTGRES_DB=auth
  auth:
    # Build parameters for the container
    build: .
    depends_on: 
      - db
    image: aljovanmp/ticket_be_auth:latest
    container_name: ticket_auth
    ports:
      # Maps ports to be accessed by the app outside of the container
      - "4001:4000"
    environment:
      MIX_ENV: "dev"
      DATABASE_USERNAME: "postgres"
      DATABASE_PWD: "Postgres"
      DATABASE_HOSTNAME: db
      DATABASE_PORT: 5432
      DATABASE_DBNAME: "auth"
      SECRET_KEY_BASE: ""
      SECRET_KEY: ""

    develop:
      watch:
        - action: sync
          path: ./lib
          target: /app/lib
        - action: sync+restart
          path: ./config
          target: /app/config
        - action: sync+restart
          path: ./lib/ticket_BE_web
          target: /app/lib/ticket_BE_web
        - action: sync
          path: ./test
          target: /app/test
        - action: rebuild
          path: mix.exs
    command: mix phx.server

  # test:
  #   # Build parameters for the container
  #   build:
  #     # Declares that the container should be built from the current directory
  #     context: .
  #   ports:
  #     # Maps ports to be accessed by the app outside of the container
  #     - "4001:4002"
  #   environment:
  #     MIX_ENV: "test"
  #   develop:
  #     watch:
  #       - action: sync+restart
  #         path: ./test
  #         target: /app/test
  #       - action: sync+restart
  #         path: ./config
  #         target: /app/config
  #       - action: sync+restart
  #         path: ./lib
  #         target: /app/lib
  #       - action: rebuild
  #         path: mix.exs
  #   command: ./test_entrypoint.sh
  
  dummy:
    image: alpine:latest
    init: true
    command: ["sh", "-c", "while true; do sleep 2; done"]